language: node_js
node_js:
  - "stable"


cache:
  yarn: true
  directories:
  - node_modules


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"


install:
  - yarn


jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: test
      script:
        - yarn test

    - stage: build
      script:
        - yarn build

    - stage: deploy
      if: branch = develop
      script: skip
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master
