language: node_js
node_js:
  - "stable"


cache:
  yarn: true
  directories:
  - node_modules


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"


install:
  - yarn


jobs:
  include:
    - stage: "Continous Integration"
      name: "lint"
      script:
        - yarn lint
    - script:
        - yarn test
      name: "test"
    - script:
        - yarn build
      name: "build"

    - stage: "Continous Deployment"
      if: branch = develop
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: develop
