language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
    - develop
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
jobs:
  include:
    - stage: "Continous Deployment"
      name: "lint"
      script:
        - yarn lint
      name: "test"
      script:
        - yarn test
      name: "build"
      script:
        - yarn build
      name: "deploy"
      script: skip
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master
